### PR TITLE
Feat/add skus resource

### PR DESCRIPTION
**Pull request by incentrotolgaakyazi**

### CODE REVIEW

**Comment by demeyerthom** [comment]
@incentrotolgaakyazi do we still want this resource? I don't think it should be part of the configuration, as SKU's should not be managed by infra. Is there a reason we do need this?

**Comment by incentrotolgaakyazi** [comment]
@demeyerthom I think you're right. SKUs should not be managed by infra. I will test if this resource is required in the current `tax-categories` resource or not.

**Comment by demeyerthom** [comment]
@incentrotolgaakyazi if it is I would suggest we also don't do the tax categories, as that would probably mean that one is also not something persistent

**Comment by demeyerthom** [comment]
Closing this as this is not something that should be managed by terraform

**Pull request closed without merging**
